# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170325_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='links',
            new_name='likes',
        ),
    ]
